=== hamza-boudouche/xml-db-service/utils/xml/schemas/projects.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="project" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:integer" name="uid"/>
              <xs:element type="xs:string" name="titre"/>
              <xs:element type="xs:integer" name="note"/>
              <xs:element name="motscles">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="motcle" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="versions">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="version">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="commentaire"/>
                          <xs:element type="xs:string" name="contenu"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="groupes">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="groupe">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element type="xs:integer" name="uid" minOccurs="0"/>
                          <xs:element name="membres" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="membre">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:integer" name="uid"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="projects" minOccurs="0">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="project">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element type="xs:integer" name="uid"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:integer" name="profId"/>
              <xs:element type="xs:string" name="status"/>
              <xs:element type="xs:string" name="type"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== hamza-boudouche/xml-db-service/utils/xml/examples/projects.xml
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../schemas/projects.xsd">
	<project>
		<uid>1</uid>
		<titre>hamza</titre>
		<note>19</note>
		<motscles>
			<motcle>
				Java
			</motcle>
			<motcle>
				web
			</motcle>
		</motscles>
		<comments>
			<comment>
				<prof>hamza</prof>
				<contenu>contenu comment</contenu>
			</comment>
		</comments>
		<versions>
			<version>
				<commentaire>something comment</commentaire>
				<contenu>nameOfFile.pdf</contenu>
			</version>
		</versions>
		<groupes>
			<groupe>
				<uid>1</uid>
				<membres>
					<membre>
						<uid>1</uid>
						<name>hamza boudouche</name>
					</membre>
				</membres>
				<projects>
					<project>
						<uid>1</uid>
					</project>
				</projects>
			</groupe>
		</groupes>
		<profId>2</profId>
		<status>FINI</status>
		<type>PROJET_INTEGRE</type>
	</project>

	<project>
		<uid>2</uid>
		<titre>hamza</titre>
		<note>18</note>
		<motscles>
			<motcle>
				Python
			</motcle>
			<motcle>
				Web
			</motcle>
		</motscles>
		<versions>
			<version>
				<commentaire>something comment 2</commentaire>
				<contenu>nameOfFile2.pdf</contenu>
			</version>
		</versions>
		<groupes>
			<groupe>
				<uid>1</uid>
				<membres>
					<membre>
						<uid>1</uid>
						<name>hamza boudouche</name>
					</membre>
				</membres>
				<projects>
					<project>
						<uid>1</uid>
					</project>
				</projects>
			</groupe>
		</groupes>
		<profId>1</profId>
		<status>EN_COURS</status>
		<type>PROJET_FIN_ETUDES</type>
	</project>
</root>
