=== hamza-boudouche/xml-db-service/utils/xml/schemas/users.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="root">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
        <xs:complexType>
          <xs:all>
            <xs:element type="xs:string" name="uid"/>
            <xs:element type="xs:string" name="displayName"/>
            <xs:element type="xs:string" name="imageUrl"/>
            <xs:element type="xs:string" name="type"/>
            <xs:element type="xs:string" name="mle" minOccurs="0"/>
            <xs:element type="xs:string" name="niveauetudes" minOccurs="0"/>
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>
</xs:schema>

=== hamza-boudouche/xml-db-service/utils/xml/examples/users.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../schemas/users.xsd">
	<user>
		<uid>hamza@hamza</uid>
		<displayName>hamzaAdmin</displayName>
		<imageUrl>hamza</imageUrl>
		<type>admin</type>
	</user>

	<user>
		<uid>hamza@hamz</uid>
		<displayName>hamza</displayName>
		<imageUrl>hamza</imageUrl>
		<type>student</type>
		<mle>61947</mle>
		<niveauetudes>BAC3</niveauetudes>
	</user>

	<user>
		<uid>hamza@ham</uid>
		<displayName>hamza</displayName>
		<imageUrl>hamza</imageUrl>
		<type>prof</type>
	</user>
</root>
